//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPPEntities : DbContext
    {
        public SPPEntities()
            : base("name=SPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Project> ProjectSet { get; set; }
        public virtual DbSet<Professor> ProfessorSet { get; set; }
        public virtual DbSet<Record> RecordSet { get; set; }
        public virtual DbSet<Document> DocumentSet { get; set; }
        public virtual DbSet<Participation> ParticipationSet { get; set; }
        public virtual DbSet<Election> ElectionSet { get; set; }
        public virtual DbSet<LinkedOrganization> LinkedOrganizationSet { get; set; }
        public virtual DbSet<ProjectManager> ProjectManagerSet { get; set; }
    }
}
