//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int idProject { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string activities { get; set; }
        public string methodology { get; set; }
        public string schedule { get; set; }
        public string generalPurpose { get; set; }
        public string mediateObjective { get; set; }
        public string inmediateObjective { get; set; }
        public Nullable<int> studentsRequired { get; set; }
        public Nullable<int> studentsAssigned { get; set; }
        public string status { get; set; }
    
        public virtual Participation Participation { get; set; }
        public virtual Election Election { get; set; }
        public virtual ProjectManager ProjectManager { get; set; }
        public virtual LinkedOrganization LinkedOrganization { get; set; }
    }
}
